### PR TITLE
Add absolute path support.

### PR DESCRIPTION
**Pull request by jamesjuuichi**

### CODE REVIEW

**Comment by mikefrey** [comment]
To keep it concise and fit with my coding style, would you mind modifying your change to just read: 
```
var filepath = Path.isAbsolute(file) ? file : Path.join(cwd, file)
```

Can you also add a test for the change?

**Comment by mikefrey** [comment]
@nktanh Also, I apologize for the long lack of response.

**Comment by nktanh** [comment]
@mikefrey Thanks for the comments, I have modified the code along with test cases. Please take a look

**Comment by mikefrey** [comment]
Thanks @nktanh 
It's been published to npm @1.2.0

**Pull request merged**
